### ISSUE TITLE
Agenda not shown after change in default deadline warning date

### ISSUE THREAD

**Issue by dinesh3434** [DanielDe/org-web#39]
I changed the default deadline warning date from 5 to 2 and saved the same as shown in the below screenshot. 
![DeepinScreenshot_select-area_20190327114731](https://user-images.githubusercontent.com/8008967/55054765-e89db480-5086-11e9-85b0-02f8389dce8c.png)

After this change I am not able to open the agenda screen and I get the following screen.

![DeepinScreenshot_select-area_20190327115207](https://user-images.githubusercontent.com/8008967/55054718-c73cc880-5086-11e9-9e93-45491751ecb3.png)

**Comment by DanielDe** [comment]
Aw shoot. I'm not able to reproduce, unfortunately. What browser are you using for this? If it's a desktop browser, would you mind opening up your developer console and copying and pasting the error messages you find there?

**Comment by dinesh3434** [comment]
Hi Daniel,

             Thanks for getting back to me quickly. Please find the below
screenshot of the error and the corresponding error code. Let me know if
you need more information regarding this issue.


[image: image.png]

[image: image.png]

Regards,
Dinesh.

**Comment by DanielDe** [comment]
Thanks again for the report, @dinesh3434! I just pushed out a fix for this in https://github.com/DanielDe/org-web/commit/a82999168e97ef4def5a09042c61797e87569f6d

**Comment by dinesh3434** [comment]
thanks for the quick action on this :). I am not getting any error while viewing the agenda now, but I am still getting error when I add a item in a list in the org file and try to save the same. Please find the below screenshot.

![image](https://user-images.githubusercontent.com/8008967/55150431-21668800-5172-11e9-981f-fd136c9e957b.png)

![image](https://user-images.githubusercontent.com/8008967/55150601-786c5d00-5172-11e9-9d99-2db8294441fb.png)

**Comment by DanielDe** [comment]
Awesome, I’ll tackle that too! Thanks again so much, Dinesh

**Comment by DanielDe** [comment]
That's fixed now, @dinesh3434! Thanks again!
